feat: 🎸 je consulte le détail d'un article (v2)
SocialGouv/1000jours pull request #111
Opened 2021-04-08 08:04 UTC by benguedj

2021-04-08 08:13 UTC, risseraka commented on front/types.tsx
> +export enum InShortIcon {
Il va falloir demander une liste plus ou moins définitive au métier pour ne pas avoir à mettre à jour l'appli trop souvent ! 😄

2021-04-08 08:18 UTC, Alezco requested changes

2021-04-08 08:18 UTC, Alezco commented on front/screens/ArticleDetail.tsx
> +    const iconSize = 40;
Tu sais que j'aime bien les objets plutôt que les if ^^ Là on peut faire un objet avec en clé `InShortIcon.x` et en valeur le composant

2021-04-08 08:18 UTC, Alezco commented on front/screens/ArticleDetail.tsx
> +    if (article.enbrefTexte1)
Idem, cette fonction peut être refacto avec un objet pour n'avoir qu'un seul `if` et un seul `push`

2021-04-08 08:18 UTC, Alezco commented on front/screens/ArticleDetail.tsx
> +          {/* Visuel */}
Plutôt que des commentaires, on pourrait sortir ces bouts de JSX dans des composants pour gagner en lisibilité

2021-04-08 08:18 UTC, Alezco commented on front/screens/ArticleDetail.tsx
> +          {/* Visuel */}
Le fichier fait presque 400 lignes, c'est trop pour un seul fichier

2021-04-08 08:18 UTC, Alezco commented on front/screens/ArticleDetail.tsx
> +              {inShortArray.map((item, i) => (
```suggestion
              {inShortArray.map((item, index) => (
```

2021-04-08 08:18 UTC, Alezco commented on front/screens/ArticleDetail.tsx
> +            {linksArray.map((item, i) => (
```suggestion
            {linksArray.map((item, index) => (
```

2021-04-08 08:20 UTC, risseraka commented on front/types.tsx
> +export enum InShortIcon {
(D'ailleurs, c'est aussi important pour le backoffice, je remonte l'alerte.)

2021-04-08 15:30 UTC, Alezco requested changes

2021-04-08 15:30 UTC, Alezco commented on front/components/article/InShort.tsx
> +    fontFamily: "comfortaa-regular",
Utiliser l'enum des font family

2021-04-08 15:30 UTC, Alezco commented on front/screens/ArticleDetail.tsx
> +    if (article.lienUrl1) addLink(article.lienTitre1, article.lienUrl1);
J'imagine plutôt quelque chose comme ça :
```
const {lienUrl1, lienTitre1, lienUrl2, lienTitre2, etc} = article;
const links = [{title: lienTitre1, link: lienUrl1}, etc];
links.forEach({link, title} => if (link) addLink(title, link))
```

2021-04-08 16:14 UTC, benguedj commented on front/screens/ArticleDetail.tsx
> +    if (article.lienUrl1) addLink(article.lienTitre1, article.lienUrl1);
Du coup, autant initialiser directement le tableau comme ça non ? : 

const linksArray = [
    {title: article.lienTitre1, link: article.lienUrl1},
    {title: article.lienTitre2, link: article.lienUrl2},
    {title: article.lienTitre3, link: article.lienUrl3},
    {title: article.lienTitre4, link: article.lienUrl4},
  ];

et le "if" je le fais au niveau du composant.

2021-04-09 11:20 UTC, Alezco requested changes

2021-04-09 11:20 UTC, Alezco commented on front/screens/ArticleDetail.tsx
> +          {/* Visuel */}
Même si ça fera des petits composants, je suis quand même favorable à passer Visuel, Titre, et Thématiques dans des fichiers séparés pour réduire la taille de ce fichier et gagner en lisbilité en nommant chaque partie du composant

2021-04-09 11:20 UTC, Alezco commented on front/components/article/InShort.tsx
> +    fontFamily: "comfortaa-regular",
@benguedj

2021-04-09 13:11 UTC, Alezco approved these changes

2021-04-09 13:12 UTC, merged