feat: 🎸 Ajoute les notifications du moodboard
SocialGouv/1000jours pull request #1172
Opened 2022-04-19 10:04 UTC by benguedj

2022-04-20 09:28 UTC, yannickjacqueline requested changes

2022-04-20 09:28 UTC, yannickjacqueline commented on front/src/components/notification/notificationScheduler.component.tsx
> +import { getObjectValue, storeObjectValue } from "../../utils/storage.util";
Plutôt utiliser `NotificationUtils` et `StorageUtils` si tu n'as pas de warnings

2022-04-20 09:28 UTC, yannickjacqueline commented on front/src/components/notification/notificationScheduler.component.tsx
> +  return null;
Pourquoi  avoir fait un composant si tu peux directement  appeler `scheduleMoodboardNotifications` ?

2022-04-20 09:28 UTC, yannickjacqueline commented on front/src/utils/app.util.ts
> +import { cancelAllScheduledNotifications } from "./notification.util";
Utiliser `NotificationUtils`

2022-04-20 09:28 UTC, yannickjacqueline commented on front/src/utils/notification.util.ts
> +  console.log("cancel All Scheduled Notifications");
Log à supprimer ?

2022-04-20 09:28 UTC, yannickjacqueline commented on front/src/utils/notification.util.ts
> +    await cancelScheduledNotifications(notifIdsMoodboard as string[]);
Les paramètres `notifIdsEvents` et `notifIdsMoodboard` devraient être castés avant d'être passés en paramètre de `cancelScheduledNotifications`

2022-04-20 09:28 UTC, yannickjacqueline commented on front/src/utils/notification.util.ts
> +    }
Tu peux peut-être utiliser un opérateur du genre map ou foreach plutôt, ça t'éviterait aussi d'avoir à mettre le  `if (notifIds.length > 0)`

2022-04-22 07:10 UTC, benguedj commented on front/src/components/notification/notificationScheduler.component.tsx
> +  return null;
Oui au final on en aura pas besoin je pense

2022-04-22 09:28 UTC, yannickjacqueline requested changes

2022-04-22 09:28 UTC, yannickjacqueline commented on front/App.tsx
> +      void scheduleMoodboardNotifications();
```suggestion
      await scheduleMoodboardNotifications();
```

2022-04-22 09:28 UTC, yannickjacqueline commented on front/src/utils/notification.util.ts
> +    const ids = notifIdsEvents as string[];
```suggestion
    const ids = notifIdsMoodboard as string[];
```

2022-04-22 09:31 UTC, benguedj commented on front/src/utils/notification.util.ts
> +    const ids = notifIdsEvents as string[];
Ah oui c'est mieux avec la bonne variable, bien vu

2022-04-22 09:33 UTC, benguedj commented on front/App.tsx
> +      void scheduleMoodboardNotifications();
Pk tu veux mettre un await ? On est pas obligé d'attendre cette fonction elle peut tourner en arrière plan.

2022-04-22 09:35 UTC, yannickjacqueline commented on front/App.tsx
> +      void scheduleMoodboardNotifications();
C'est simplement par cohérence avec les autres promesses qui sont appelées, `manageStorage` et `updateAppActiveCounter` faut les attendre ?

2022-04-22 09:40 UTC, benguedj commented on front/App.tsx
> +      void scheduleMoodboardNotifications();
`manageStorage`, oui il faut l'attendre mais `updateAppActiveCounter` je pense pas après c'est pas des opérations très couteuses donc on peut tt mettre en await pour être sûr

2022-04-22 09:45 UTC, yannickjacqueline commented on front/App.tsx
> +      void scheduleMoodboardNotifications();
OK OK, on peut laisser comme ça du coup à la limite

2022-04-22 09:45 UTC, yannickjacqueline approved these changes

2022-05-03 09:20 UTC, merged