feat: 🎸 Ajoute texteTitre1 et texteTitre2 (article)
SocialGouv/1000jours pull request #127
Opened 2021-04-13 16:21 UTC by benguedj

✅ Closes: #102

2021-04-13 16:30 UTC, Alezco requested changes

2021-04-13 16:30 UTC, Alezco commented on front/components/article/DidYouKnow.tsx
> +  return description && description.length > 0 ? (
```suggestion
  return description?.length > 0 ? (
```

2021-04-13 16:30 UTC, Alezco commented on front/components/article/SubTitle.tsx
> +  return <CommonText style={[styles.title]}>{title}</CommonText>;
Peut se simplifier en retirant l'accolade et le `return`

2021-04-14 12:59 UTC, benguedj commented on front/components/article/DidYouKnow.tsx
> +  return description && description.length > 0 ? (
J'ai mis // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition car eslint considère que string ne peut pas être nullable

2021-04-14 13:00 UTC, Alezco approved these changes

2021-04-14 13:21 UTC, merged