feat: 🎸 Ajoute la noutification des articles non lus
SocialGouv/1000jours pull request #1285
Opened 2022-07-01 07:11 UTC by benguedj

✅ Closes: #1126

2022-07-01 07:15 UTC, alebret commented on front/App.tsx
> +import StoreCurrentStepArticleIds from "./src/components/storage/storeCurrentStepArticleIds.component";
Il ne faut pas mettre ce component dans le fichier `ìndex.ts` pour que l'import soit `../../components` ?

2022-07-01 07:29 UTC, alebret commented on front/src/utils/notification.util.ts
> +  return {
Il y a l'air d'avoir pas mal de possibilités, tu n'as pas moyen de faire des petits TUs  ?

2022-07-06 14:38 UTC, alebret commented on front/src/utils/notification.util.ts
> +        if (isAfter(date, new Date())) needToBeScheduled = true;
`isAfter` renvoie un `boolean`, non ? du coup, tu pourrais faire directement : 
`needToBeScheduled = isAfter(date, new Date())`

2022-07-06 14:41 UTC, alebret commented on front/src/utils/notification.util.ts
> +  } else if (nbArticlesToRead === 0) {
t'es pas obligé de mette le `else` vu sur tes 2 `if` font un `return`

2022-07-06 14:44 UTC, alebret commented on front/src/utils/step.util.ts
> +export const countCurrentStepArticlesRead = async (): Promise<number> => {
Je suis un peu relou ... mais ya peu être moyen de faire des TU.

2022-07-06 14:47 UTC, yannickjacqueline requested changes

2022-07-06 14:59 UTC, benguedj commented on front/src/components/menu/infosDev.component.tsx
> +  const renderNotificationsCountItem = (key: string, value: number) => {
Ici je pense que c'est pas très utile vu que c'est que de l'affichage 'debug' pour nous et les testeurs.

2022-07-06 15:00 UTC, alebret commented on front/src/components/menu/infosDev.component.tsx
> +  const renderNotificationsCountItem = (key: string, value: number) => {
ah oui effectivement, j'avais pas fait attention

2022-07-07 14:23 UTC, alebret approved these changes

2022-07-08 13:42 UTC, alebret approved these changes

2022-07-08 13:56 UTC, merged