chore(deploy): supprime TypeScript et remplace Hasura par le plugin GraphQL de Strapi
SocialGouv/1000jours pull request #138
Opened 2021-04-15 11:07 UTC by risseraka

2021-04-15 15:41 UTC, Alezco requested changes

2021-04-15 15:41 UTC, Alezco commented on back/strapi/api/etape/config/schema.graphql.js
> +const getCurrentEtapeResolver = async (obj, options, { context }) => {
Possible de trouver un meilleur nom que `obj` (qui n'est en plus pas utilisé) ?

2021-04-15 15:41 UTC, Alezco commented on back/strapi/api/etape/config/schema.graphql.js
> +        description: "Retourne l'étape courante en fonction des informations ",
```suggestion
        description: "Retourne l'étape courante en fonction des informations",
```

2021-04-15 15:41 UTC, Alezco commented on back/strapi/api/etape/services/index.js
> +} = require("date-fns");
Possible de plutôt utiliser `import` ici ?

2021-04-15 15:41 UTC, Alezco commented on back/strapi/api/etape/services/index.js
> +    throw new Error("missing informations");
Cette erreur est en anglais alors que les autres sont en français. C'est voulu ?

2021-04-15 15:41 UTC, Alezco commented on back/strapi/config/api.json
> +    {
Vérifier si l'indentation est bonne

2021-04-15 15:41 UTC, Alezco commented on front/.env.example
> -BO_URL=https://backoffice-preprod-les1000jours.dev2.fabrique.social.gouv.fr
Note pour plus tard : une fois cette PR mergée, supprimer `BO_URL` des secrets GitHub

2021-04-15 15:47 UTC, risseraka commented on back/strapi/api/etape/services/index.js
> +    throw new Error("missing informations");
C'est une erreur plutôt tech, j'ai hésité à traduire. Tu en penses quoi ?

2021-04-15 15:51 UTC, risseraka commented on back/strapi/api/etape/services/index.js
> +} = require("date-fns");
Pour pouvoir utiliser `import`, il faudrait compiler avec babel ou utiliser un flag node. 😞

2021-04-15 15:52 UTC, Alezco commented on back/strapi/api/etape/services/index.js
> +    throw new Error("missing informations");
Tout dépend si elle est destinée à des logs ou à être renvoyée au front. Là ça ne semble pas être pour le front donc c'est peut-être à garder en anglais. Par contre les autres erreurs pourraient passer de français à anglais, sauf pour les termes "métier"

2021-04-15 15:56 UTC, Alezco commented on back/strapi/api/etape/services/index.js
> +} = require("date-fns");
Effectivement, babel est sûrement nécessaire pour utiliser cette syntaxe. Tu penses que ça vaut le coup de l'installer ?

2021-04-15 16:05 UTC, risseraka commented on back/strapi/api/etape/services/index.js
> +} = require("date-fns");
Pas convaincu de la nécessité de s'ajouter un système de build, et la lenteur + process + config que ça implique, juste pour utiliser import/export, mais je veux bien me laisser convaincre.

2021-04-15 16:06 UTC, risseraka commented on back/strapi/api/etape/services/index.js
> +    throw new Error("missing informations");
C'était mieux avant alors, je rollback ? 😄

2021-04-15 16:11 UTC, risseraka commented on back/strapi/api/etape/config/schema.graphql.js
> +const getCurrentEtapeResolver = async (obj, options, { context }) => {
La doc n'est pas claire sur ce que c'est, et je reçois toujours `undefined`, tu proposes quoi ? Quelque chose comme `_unused` ?
https://strapi.io/documentation/developer-docs/latest/development/plugins/graphql.html

2021-04-16 08:11 UTC, Alezco commented on back/strapi/api/etape/services/index.js
> +} = require("date-fns");
Alors il y a les imports mais aussi les opérateurs `?.`, `??` et aussi l'interpolation de string ``${}`` que j'aime bien. A toi de voir

2021-04-16 08:48 UTC, risseraka commented on back/strapi/api/etape/services/index.js
> +} = require("date-fns");
`${str}` est natif si tu parles bien de ça.

L'opérateur `?.` est bien cool, c'est vrai (tiens, je connaissais pas `??`, sympa).

Je te propose de faire passer cette PR, déjà bien lourde, une fois que tu considères que toutes tes remarques ont été prises en compte et ajouter babel dans un second temps.
Deal ? 😄

2021-04-16 08:49 UTC, Alezco commented on back/strapi/api/etape/config/schema.graphql.js
> +const getCurrentEtapeResolver = async (obj, options, { context }) => {
Oui `_unused` ça me va

2021-04-16 08:50 UTC, Alezco commented on back/strapi/api/etape/services/index.js
> +} = require("date-fns");
Deal 👍

2021-04-16 08:51 UTC, risseraka commented on back/strapi/api/etape/config/schema.graphql.js
> +const getCurrentEtapeResolver = async (obj, options, { context }) => {
Le param `options` n'est pas utilisé non plus, `_unused1` et `_unused2` ? 😭

2021-04-16 08:56 UTC, Alezco commented on back/strapi/api/etape/config/schema.graphql.js
> +const getCurrentEtapeResolver = async (obj, options, { context }) => {
Super API 😁 Oui faisons comme ça

2021-04-16 09:20 UTC, Alezco requested changes

2021-04-16 09:20 UTC, Alezco commented on back/strapi/api/etape/services/index.js
> +    throw new Error("terme's date is too much into the future");
```suggestion
    throw new Error("terme's date is too far in the future");
```

2021-04-16 09:28 UTC, Alezco approved these changes

2021-04-16 09:33 UTC, risseraka commented
@benguedj @Alezco J'ai potentiellement pas changé tout le front comme il faut.
Je l'ai fait comme j'ai pu, mais est-ce que c'est possible pour vous de tester la branche en local avant de merge ou vous pensez que cet après-midi est suffisant pour corriger les éventuels bugs ? 🤔

2021-04-16 13:10 UTC, Alezco approved these changes

2021-04-16 13:10 UTC, merged