feat(ci): ajoute les workflows de build et publish pour la production
SocialGouv/1000jours pull request #145
Opened 2021-04-16 14:01 UTC by Alezco

2021-04-16 14:12 UTC, risseraka requested changes

2021-04-16 14:12 UTC, risseraka commented on front/README.md
> +D'abord, installez les dépendances :
```suggestion
D'abord, installer les dépendances :
```

2021-04-16 14:12 UTC, risseraka commented on front/README.md
> +- Allez sur le [GitHub Actions](https://github.com/SocialGouv/1000jours/actions) du projet
```suggestion
- Aller sur le [GitHub Actions](https://github.com/SocialGouv/1000jours/actions) du projet
```

2021-04-16 14:12 UTC, risseraka commented on front/README.md
> +- Sélectionnez le workflow souhaité dans la colonne de gauche
```suggestion
- Sélectionner le workflow souhaité dans la colonne de gauche
```

2021-04-16 14:12 UTC, risseraka commented on front/README.md
> +- Cliquez sur le menu `Run workflow`
```suggestion
- Cliquer sur le menu `Run workflow`
```

2021-04-16 14:12 UTC, risseraka commented on front/README.md
> +- Sélectionnez la branche `master`
```suggestion
- Sélectionner la branche `master`
```

2021-04-16 14:12 UTC, risseraka commented on front/README.md
> +- Cliquez sur le bouton `Run workflow`
```suggestion
- Cliquer sur le bouton `Run workflow`
```

2021-04-20 14:21 UTC, benguedj requested changes

2021-04-20 14:21 UTC, benguedj commented on .github/workflows/expo-build-dev.yml
>    Publish-android:
```suggestion
  Build-android
```

2021-04-20 14:21 UTC, benguedj commented on .github/workflows/expo-build-dev.yml
>    Publish-ios:
```suggestion
  Build-ios:
```

2021-04-20 14:21 UTC, benguedj commented on .github/workflows/expo-build-prod.yml
> +  Publish-android:
```suggestion
  Build-android:
```

2021-04-20 14:21 UTC, benguedj commented on .github/workflows/expo-build-prod.yml
> +  Publish-ios:
```suggestion
  Build-ios:
```

2021-04-20 14:44 UTC, benguedj approved these changes

2021-04-21 15:36 UTC, merged