feat(dpp): ajout de la bannière d'accès au questionnaire
SocialGouv/1000jours pull request #149
Opened 2021-04-19 13:35 UTC by yannickjacqueline

2021-04-19 15:31 UTC, Alezco requested changes

2021-04-19 15:31 UTC, Alezco commented on front/constants/Labels.ts
> +    threeFirstMonths: {
```suggestion
    firstThreeMonths: {
```

2021-04-19 15:31 UTC, Alezco commented on front/screens/ListArticles.tsx
> +/* Je pense que je modifierai ça plus tard, je trouve pas ça très propre de stocker un ID du back dans le front comme ça,
👍

2021-04-19 15:31 UTC, Alezco commented on front/screens/ListArticles.tsx
> +        <View style={[styles.topContainer]}>
Quand il n'y a qu'un style, peut se simplifier en enlevant les crochets

2021-04-20 08:20 UTC, yannickjacqueline commented on front/screens/ListArticles.tsx
> +        <View style={[styles.topContainer]}>
Ouais effectivement, j'en profite pour le reste des styles où il n'y en a qu'un ;)

2021-04-20 08:29 UTC, yannickjacqueline commented on front/screens/ListArticles.tsx
> +  const stepIs3FirstMonths = route.params.step.id == ETAPE_ENFANT_3_PREMIERS_MOIS;
J'avais justement mis un strict equality avant, mais ça tombait tout le temps à false, je pense que c'est parce que le route.params.step.id est une string et avec le double =, il la converti avant de faire la comparaison

2021-04-20 08:39 UTC, Alezco requested changes

2021-04-20 08:39 UTC, Alezco commented on front/screens/ListArticles.tsx
> +  const stepIsFirstThreeMonths = route.params.step.id == ETAPE_ENFANT_3_PREMIERS_MOIS;
```suggestion
  const stepIsFirstThreeMonths = route.params.step.id === ETAPE_ENFANT_3_PREMIERS_MOIS;
```

2021-04-21 14:23 UTC, merged