feat(dpp): Ajout des questions dans le back + refacto front
SocialGouv/1000jours pull request #169
Opened 2021-04-28 16:35 UTC by yannickjacqueline

Le modèle de données pour le questionnaire DPP a été ajouté dans le back, j'ai donc fait le branchement avec le front et pas mal de refacto.

Pour tester:
- ajouter des questions et réponses via l'interface de Strapi (avec la locale ainsi que les points que rapportent les réponses)
- vérifier que vous récupérer bien le questionnaire côté mobile, et que vous avez un résultat à la fin

2021-04-28 16:42 UTC, risseraka commented on front/screens/epdsSurvey/epdsResult.component.tsx
> +  const labels = result <= 9 ? labelsResultats.moinsDeNeuf : result <= 12 ? labelsResultats.entreDixEtDouze : labelsResultats.plusDeTreize;
La ligne semble bien longue.
Prettier ne passe pas sur ces fichiers ?

2021-04-28 16:42 UTC, risseraka commented on front/constants/Labels.ts
> +        explication: "Un score de 9 ou moins est très rassurant au regard de la dépression. Mais, si vous en ressentez le besoin, vous pouvez consulter votre médecin traitant ou le professionnel qui
J'imagine qu'il faudra le mettre dans le backend à un moment pour pouvoir gérer les différentes langues (ou seules les questions / réponses doivent être traduites) ?

2021-04-28 16:42 UTC, risseraka commented on front/constants/Labels.ts
> +      introduction: "Vous avez obtenu le score suivant : ",
L'espace après les deux points est-elle volontaire ? C'est pour l'affichage ?

2021-04-29 08:18 UTC, yannickjacqueline commented on front/screens/epdsSurvey/epdsResult.component.tsx
> +  const labels = result <= 9 ? labelsResultats.moinsDeNeuf : result <= 12 ? labelsResultats.entreDixEtDouze : labelsResultats.plusDeTreize;
Effectivement :D c'est corrigé

2021-04-29 08:22 UTC, yannickjacqueline commented on front/constants/Labels.ts
> +        explication: "Un score de 9 ou moins est très rassurant au regard de la dépression. Mais, si vous en ressentez le besoin, vous pouvez consulter votre médecin traitant ou le professionnel qui
Oui complètement. En fait la question qui se pose encore, c'est dans quel contexte faudra traduire le questionnaire (par exemple, est-ce que ça sera seulement le médecin ou infirmier qui passera son téléphone à son patient non francophone, auquel cas y aura pas vraiment d'intérêt de traduire puisque ce sera le médecin ou infirmier qui interprètera la réponse).
Mais en tout cas oui, potentiellement le résultat pourra être côté backend

2021-04-29 08:23 UTC, yannickjacqueline commented on front/constants/Labels.ts
> +      introduction: "Vous avez obtenu le score suivant : ",
Oui c'est volontaire, après je sais pas c'est quoi la meilleure "bonne pratique" pour ça, si on peut le laisser dans le label ou s'il faut le mettre côté component

2021-04-29 08:30 UTC, Alezco requested changes

2021-04-29 08:30 UTC, Alezco commented on front/constants/Colors.ts
> +  secondaryRedLight: "#e86404",
```suggestion
  secondaryRedLight: "#E86404",
```
Pour garder la cohérence avec les autres couleurs

2021-04-29 08:30 UTC, Alezco commented on front/screens/epdsSurvey/epdsQuestion.component.tsx
> +        <CommonText style={[styles.title]}>
Peut se simplifier en retirant les `[]`

2021-04-29 08:30 UTC, Alezco commented on front/screens/epdsSurvey/epdsResult.component.tsx
> +  const labels = result <= 9 ? labelsResultats.moinsDeNeuf : result <= 12 ? labelsResultats.entreDixEtDouze : labelsResultats.plusDeTreize;
Autre chose, les double ternaires ne sont pas top pour la lisibilité je trouve. A diviser en deux ou faire une fonction `getLabel` avec des `if`

2021-04-29 08:30 UTC, Alezco commented on front/screens/epdsSurvey/epdsResult.component.tsx
> +  const style = result <= 9 ? styles.green : result <= 12 ? styles.yellow : styles.red;
Idem ici, double ternaire à éviter

2021-04-29 08:30 UTC, Alezco commented on front/screens/epdsSurvey/epdsResult.component.tsx
> +  result = 15;
Ca marche de muter des props ? Si c'est pout mettre une valeur par défaut, il faut l'ajouter directement ligne 15. Sinon, il faut que `result` soit un state pour le modifier

2021-04-29 08:30 UTC, Alezco commented on front/screens/epdsSurvey/epdsResult.component.tsx
> +    result <= 9
Double ternaire à éviter pour la lisibilité

2021-04-29 08:30 UTC, Alezco commented on front/screens/epdsSurvey/epdsSurveyContent.component.tsx
> +    questionsAndAnswers[swiperCurrentIndex].isAnswered;
```suggestion
    questionsAndAnswers[swiperCurrentIndex]?.isAnswered;
```

2021-04-29 08:30 UTC, Alezco commented on front/screens/epdsSurvey/epdsSurveyContent.component.tsx
> +    if (choosenAnswers && choosenAnswers.length === 1) {
```suggestion
    if (choosenAnswers?.length === 1) {
```

2021-04-29 08:30 UTC, Alezco commented on front/screens/epdsSurvey/epdsSurveyContent.component.tsx
> +      return choosenAnswers[0].points;
Pourquoi `[0]` ?

2021-04-29 08:30 UTC, Alezco commented on front/screens/epdsSurvey/epdsSurveyContent.component.tsx
> +          ? question.answers.map((answer) => {
Je pense qu'il faut diviser cette fonction en plusieurs fonctions plus petites. Par exemple avec une fonction qui s'occupe juste de calculer le `newScore`, une qui s'occupe juste du corps du `.map` (donc qui ne traite qu'un seul élément), etc

2021-04-29 08:30 UTC, Alezco commented on front/screens/epdsSurvey/epdsSurveyContent.component.tsx
> +                  return (
Peut se simplifier en supprimant l'accolade et le `return`

2021-04-29 08:30 UTC, Alezco commented on front/screens/epdsSurvey/epdsSurveyScreen.component.tsx
> +// eslint-disable-next-line @typescript-eslint/no-duplicate-imports
Est-ce que cette ligne est encore nécessaire ?

2021-04-29 08:30 UTC, Alezco commented on front/screens/epdsSurvey/epdsSurveyScreen.component.tsx
> +export interface QuestionAndAnswers {
Puisque ces interfaces sont exportées, peut-être les isoler dans leur propre fichier pour éviter d'importer un composant alors qu'on veut juste importer des types

2021-04-29 08:30 UTC, Alezco commented on front/screens/epdsSurvey/epdsSurveyScreen.component.tsx
> +const EpdsSurveyScreen: FC<Props> = ({}) => {
Est-ce que le `{}` est nécessaire ?

2021-04-29 08:30 UTC, Alezco commented on front/screens/epdsSurvey/epdsSurveyScreen.component.tsx
> +  const tempQuestionsAndAnswers: QuestionAndAnswers[] = EpdsSurveyUtils.convertToQuestionsAndAnswers(fetchedData);
```suggestion
  const questionsAndAnswers: QuestionAndAnswers[] = EpdsSurveyUtils.convertToQuestionsAndAnswers(fetchedData);
```

2021-04-29 08:30 UTC, Alezco commented on front/utils/epdsSurvey.util.ts
> +export function convertToQuestionsAndAnswers(
```suggestion
export const convertToQuestionsAndAnswers = (
```

2021-04-29 08:30 UTC, Alezco commented on front/utils/epdsSurvey.util.ts
> +  return questionnaire.map((element) => {
A tester, je ne suis pas sûr que ça marche : 
```
questionnaire.map((element, index) => ({
   id: index,
   label: element[`reponse_${index + 1}_libelle`],
   points: element[`reponse_${index + 1}_points`],
   isChecked: false,
}));
```

2021-04-29 08:37 UTC, yannickjacqueline commented on front/screens/epdsSurvey/epdsResult.component.tsx
> +  result = 15;
Non c'était pour un test et j'ai oublié de l'enlever xD merci

2021-04-29 09:29 UTC, yannickjacqueline commented on front/screens/epdsSurvey/epdsSurveyContent.component.tsx
> +      return choosenAnswers[0].points;
Parce qu'il n'y aura qu'une seule réponse par question qui sera cochée, donc le filter n'en retournera qu'une seule à la fois

2021-04-29 09:35 UTC, Alezco commented on front/screens/epdsSurvey/epdsSurveyContent.component.tsx
> +      return choosenAnswers[0].points;
Alors plutôt qu'un `filter`, tu devrais peut-être utiliser `find` pour n'avoir qu'un élément à la fin

2021-04-29 14:39 UTC, yannickjacqueline commented on front/utils/epdsSurvey.util.ts
> +  return questionnaire.map((element) => {
Il me tape cette erreur : 
`L'élément a implicitement un type 'any', car l'expression de type 'string' ne peut pas être utilisée pour indexer le type 'QuestionnaireEpdsFromDB'.
  Aucune signature d'index avec un paramètre de type 'string' n'a été localisée sur le type 'QuestionnaireEpdsFromDB'.ts(7053)`

Il est pas content qu'on utilise des index sous forme d'une string

2021-04-29 15:22 UTC, Alezco approved these changes

2021-04-30 08:37 UTC, Alezco requested changes

2021-04-30 08:37 UTC, Alezco commented on front/screens/epdsSurvey/epdsResult.component.tsx
> +  // result = 5;
Ligne à supprimer

2021-04-30 08:37 UTC, Alezco commented on front/screens/epdsSurvey/epdsResult.component.tsx
> +  let resultIcone;
Encapsuler cette logique dans une fonction et pour éviter les if, on peut faire une map : 
```
const getIcon = (icone) => {
  const resultIcons = {
    BIEN: <IconeResultatBien />
    MOYEN: <IconeResultatMoyen />
    PASBIEN: <IconeResultatPasBien />
  };
  return resultIcons[icone] ?? <IconeResultatPasBien />;
}
```

2021-04-30 08:37 UTC, Alezco commented on front/screens/epdsSurvey/epdsResult.component.tsx
> +  let resultIcone;
Sans if/else, on découple la logique (la ligne du `return`) de la donnée (la map icon -> composant)

2021-04-30 08:37 UTC, Alezco commented on front/type/epdsSurvey.types.ts
> +export type EpdsIconResult = 'BIEN' | 'MOYEN' | 'PAS_BIEN';
En plus de ce type, on peut éventuellement ajouter une enum qui contient ces trois valeurs

2021-04-30 08:37 UTC, Alezco commented on front/utils/epdsSurvey.util.ts
> +    icone = 'BIEN';
Avec l'enum évoquée plus haut, on pourra remplacer ce "BIEN" par `EpdsIconResult.BIEN`

2021-04-30 08:37 UTC, Alezco commented on front/utils/epdsSurvey.util.ts
> +    icone = 'BIEN';
Autre remarque : plutôt que trois variables `label`, `colorStyle` et `icone`, on pourrait encapsuler directement les trois valeurs dans un seul objet

2021-04-30 13:54 UTC, Alezco commented on front/screens/epdsSurvey/epdsResult.component.tsx
> +    let iconsMap = new Map<EpdsIconResultEnum, JSX.Element >();
Désolé, j'ai parlé d'une map mais je pensais à un objet :D Bon après les deux implems marchent (les données sont séparées de la logique) donc on garde la version que tu trouves la plus claire. 

Pour le type des icônes, tant mieux si `JSX.Element` ne produit par d'erreur, mais en cas de problème tu peux utiliser `ReactNode`. La différence est expliquée ici : https://stackoverflow.com/questions/58123398/when-to-use-jsx-element-vs-reactnode-vs-reactelement

Enfin, il y a un espace entre `JSX.Element` et `>` dont il faut peut-être lancer `yarn lint-fix`

2021-04-30 14:27 UTC, Alezco approved these changes

2021-04-30 14:28 UTC, merged