Renseigner civilite avant questionnaire
SocialGouv/1000jours pull request #186
Opened 2021-05-03 18:09 UTC by yannickjacqueline

#181

2021-05-04 07:22 UTC, risseraka reviewed
Ça me va mais je laisse à @Alezco et @benguedj le soin de faire une revue plus poussée. :)

2021-05-04 15:38 UTC, Alezco requested changes

2021-05-04 15:38 UTC, Alezco commented on front/screens/epdsSurvey/epdsSurveyScreen.component.tsx
> +    async function getGenderFromStorage() {
```suggestion
    const getGenderFromStorage = async () => {
```

2021-05-04 15:38 UTC, Alezco commented on front/screens/epdsSurvey/epdsSurveyScreen.component.tsx
> +      setGenderIsEntered(genderValue ? true : false);
```suggestion
      setGenderIsEntered(genderValue);
```

2021-05-04 15:38 UTC, Alezco commented on front/utils/dataFetching.util.tsx
> +export const fetchData = (query: DocumentNode): DataFetchingType => {
L'idée est bonne pour refactoriser le loading et l'error (et ne pas le répéter dans plein de composants, mais je vois plusieurs problèmes.
- Déjà le type de retour n'est pas toujours le même, soit un JSX, soit un objet. 
- Ensuite, il pourrait trop se complexifier à l'avenir si on veut le variabiliser en voulant changer la politique de cache, le message d'erreur ou d'autres choses
- Tu utilises un hook dans ta fonction, ce qui induit en erreur. On pourrait avoir envie d'appeler cette fonction en dehors d'un composant (par exemple dans une méthode utilitaire), mais ça ne marchera pas puisqu'un hook ne peut pas être appelé en dehors d'un composant.
Une solution possible : mettre plutôt cette logique dans un composant qui appellera le hook, retournera le composant de loading/error, ou un composant enfant en lui passant data en props. 
Ca donnerait quelque chose comme ça : 
```
const FetchData: FC = ({ children, query }) => {
  const { loading, error, data } = useQuery(query, {
    fetchPolicy: "no-cache",
  }); 
  if (loading) return <LoadingComponent ... />
  if (error) return <ErrorComponent ... />
  return children(data);
}
``` 
Et son utilisation : 
```
<FetchData query={GQL_QUERY}>
  ({data}) => <View>{data.map((element) => /* ... */)}</View>
<FetchData />
```

PS: Peut-être que Apollo propose déjà ce composant plutôt que le hook `useQuery`

2021-05-04 15:38 UTC, Alezco commented on front/utils/epdsSurvey.util.ts
> +): EpdsQuestionAndAnswers[] => {
Peut se simplifier en retirant l'accolade et le `return`

2021-05-04 15:38 UTC, Alezco commented on front/utils/epdsSurvey.util.ts
> +): number | undefined => {
Peut-être plutôt `number | null` ? A voir ce que renvoie find en cas d'objet non trouvé

2021-05-04 15:38 UTC, Alezco commented on front/utils/epdsSurvey.util.ts
> +  if (result <= EpdsConstants.RESULT_WELL_VALUE) {
👍

2021-05-04 15:38 UTC, Alezco commented on front/utils/scaleNormalize.util.ts
> +const scale = SCREEN_WIDTH / 375;
Peut-être à normaliser avec les données qu'on peut avoir avec `Platform` de React Native

2021-05-04 15:38 UTC, Alezco commented on front/utils/scaleNormalize.util.ts
> +export function scaleNormalize(size: number): number {
```suggestion
export const scaleNormalize = (size: number): number => {
```

2021-05-04 15:38 UTC, Alezco commented on front/utils/scaleNormalize.util.ts
> +  if (Platform.OS === "ios") {
Peut se refacto avec un ternaire pour éviter d'utiliser `let`

2021-05-04 15:38 UTC, Alezco commented on front/screens/epdsSurvey/epdsGenderEntry.component.tsx
> +  const gendersArray: EpdsGenderType[] = [
Tu sais que je n'aime pas trop les listes avec des index comme ça 😁 . Ca peut peut-être se refacto avec un `range(3).map(index => ({ ... }))`

2021-05-04 15:45 UTC, yannickjacqueline commented on front/screens/epdsSurvey/epdsSurveyScreen.component.tsx
> +      setGenderIsEntered(genderValue ? true : false);
Y a un conflit de type, parce que le genderIsEntered est un booléen et le genderValue est une string (ou null/undefined)

2021-05-04 15:51 UTC, yannickjacqueline commented on front/utils/scaleNormalize.util.ts
> +const scale = SCREEN_WIDTH / 375;
Tu veux dire extraire dans un fichier de constantes ?

2021-05-04 16:23 UTC, yannickjacqueline commented on front/utils/dataFetching.util.tsx
> +export const fetchData = (query: DocumentNode): DataFetchingType => {
Je trouve ça limite encore plus difficile d'utilisation du coup x) Parce que du coup dans l'EpdsSurveyScreen, ça te force à appeler le FetchData sous forme d'un composant au lieu d'une simple fonction.
Pour le type de retour, je peux créer une variable de plus dans ce cas, qui se remplit ou non selon le retour.

Et pour l'histoire du hook et de cache, je suis d'accord avec toi, après visiblement avec Apollo, pour fetcher des données, on ne peut utiliser que le useQuery, donc dans tous les cas ça ne sera pas possible de l'utiliser hors d'un composant j'ai l'impression...
On peut en discuter si tu veux ;)

2021-05-04 16:46 UTC, yannickjacqueline commented on front/utils/epdsSurvey.util.ts
> +): number | undefined => {
Le find retourne bien un undefined s'il trouve rien

2021-05-04 16:47 UTC, yannickjacqueline commented on front/screens/epdsSurvey/epdsGenderEntry.component.tsx
> +  const gendersArray: EpdsGenderType[] = [
Effectivement :D c'est modifié

2021-05-04 16:50 UTC, yannickjacqueline commented on front/utils/dataFetching.util.tsx
> +export const fetchData = (query: DocumentNode): DataFetchingType => {
En attendant, j'ai modifié pour avoir une variable en plus ;)

2021-05-05 09:51 UTC, Alezco approved these changes

2021-05-05 09:53 UTC, merged