Conserver contexte questionnaire
SocialGouv/1000jours pull request #194
Opened 2021-05-06 15:49 UTC by yannickjacqueline

US #182 
Cas de test : 
- lancer le questionnaire EPDS
- répondre à 2-3 questions
- revenir sur l'Accueil (ou n'importe quel autre écran)
- relancer le questionnaire
- vous devez avoir un message demandant à continuer le précédent questionnaire ou à en recommencer un nouveau
- si vous continuez, vous revenez sur la dernière question posée
- si vous recommencer, vous repartez de 0

2021-05-07 08:25 UTC, Alezco requested changes

2021-05-07 08:25 UTC, Alezco commented on front/screens/epdsSurvey/epdsSurveyContent.component.tsx
> +      const previousQuestionsAndAnswers = await StorageUtils.getObjectValue(
Pour faire les deux appels en parallèle et gagner quelques millisecondes, tu peux utiliser `Promise.all`: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

2021-05-07 08:25 UTC, Alezco commented on front/screens/epdsSurvey/epdsSurveyContent.component.tsx
> +      void StorageUtils.multiRemove(StorageKeysConstants.epdsSurveyKeys);
A stocker dans une fonction utilitaire peut-être ? Cette fonction sera peut-être appelée à plusieurs endroits

2021-05-07 08:25 UTC, Alezco commented on front/screens/epdsSurvey/epdsSurveyContent.component.tsx
> +      const questionAndAnswers = (await StorageUtils.getObjectValue(
Idem, les deux appels asynchrones peuvent se paralléliser avec `Promise.all`

2021-05-07 08:25 UTC, Alezco commented on front/screens/epdsSurvey/epdsSurveyContent.component.tsx
> +    await StorageUtils.storeObjectValue(
Promise.all

2021-05-07 08:25 UTC, Alezco commented on front/screens/epdsSurvey/epdsSurveyContent.component.tsx
> +      renderSurveyContent()
Je n'aime pas trop les fonctions `renderX` parce que je trouve qu'elles font perdre un peu de lisibité. Plutôt que du JSX qu'on repère au premier coup d'oeil, on doit aller dans une fonction pour être sûr de ce qui est retourné. Je préfère faire des petits composants qui s'appellent entre eux pour bien séparer deux choses : du JSX pour le rendu d'éléments, et des fonctions pour de la logique métier

2021-05-07 08:25 UTC, Alezco commented on front/screens/epdsSurvey/epdsSurveyContent.component.tsx
> +        renderSurveyOrLoadPreviousSurveyScreen()
Très bien d'isoler la logique dans un composant séparé !

2021-05-07 08:25 UTC, Alezco commented on front/utils/storage.util.ts
> +  return AsyncStorage.getItem(storageKey);
Pourquoi retirer les `try catch` ?

2021-05-07 14:58 UTC, Alezco requested changes

2021-05-07 14:58 UTC, Alezco commented on front/screens/epdsSurvey/epdsSurveyContent.component.tsx
> +      await Promise.all([
Pas besoin de `async` `await` si tu fais un `.then`

2021-05-07 14:58 UTC, Alezco commented on front/screens/epdsSurvey/epdsSurveyContent.component.tsx
> +      ]).then((values) => {
```suggestion
      ]).then(([previousQuestionsAndAnswers, previousQuestionIndex]) => {
```

2021-05-07 14:58 UTC, Alezco commented on front/screens/epdsSurvey/epdsSurveyContent.component.tsx
> +      ]).then((values) => {
```suggestion
      ]).then(([questionAndAnswers: EpdsQuestionAndAnswers[], swiperIndex: number]) => {
```

2021-05-10 10:33 UTC, yannickjacqueline commented on front/screens/epdsSurvey/epdsSurveyContent.component.tsx
> +      renderSurveyContent()
Du coup, j'ai remis le contenu du questionnaire dans le `return`, et j'ai extrait la liste des questions dans un composant `EpdsSurveyQuestionsList`

2021-05-11 07:51 UTC, merged