feat: 🎸 Ajoute la nouvelle version du datePicker
SocialGouv/1000jours pull request #195
Opened 2021-05-07 10:49 UTC by benguedj

✅ Closes: #159

2021-05-07 12:08 UTC, yannickjacqueline commented on front/components/form/DatePicker.tsx
> +import Labels from "../../constants/Labels";
En utilisant le fichier `index.js` du dossier de constantes, l'import de `Colors` et `Labels` peut être simplifié : `import { Colors, Labels } from "../constants";`

2021-05-07 12:41 UTC, Alezco requested changes

2021-05-07 12:41 UTC, Alezco commented on front/components/form/DatePicker.tsx
> +  const buildButtonTitle = (newDate: Date | undefined) =>
```suggestion
  const buildButtonTitle = (newDate: Date | undefined):string =>
```

2021-05-07 12:41 UTC, Alezco commented on front/components/form/DatePicker.tsx
> +    if (newDate !== undefined) onChange(newDate);
Est-ce que ESLint autorise les `if` sans accolades ?

2021-05-07 12:41 UTC, Alezco commented on front/components/form/DatePicker.tsx
> +  const minDate = addYears(new Date(), -100);
Faire plutôt `subYears(new Date(), 100)` pour gagner en lisbilité

2021-05-07 12:41 UTC, Alezco commented on front/components/form/DatePicker.tsx
> +                  <View style={[styles.buttonContainer]}>
```suggestion
                  <View style={styles.buttonContainer}>
```

2021-05-07 12:41 UTC, Alezco commented on front/screens/Profile.tsx
> +                      : undefined
Si possible, plutôt utiliser `null` que `undefined` ? `null` est plutôt une valeur définie par le développeur, alors que `undefined` signifie plutôt "il n'y a rien ici", sans action du développeur

2021-05-07 13:48 UTC, benguedj commented on front/screens/Profile.tsx
> +                      : undefined
En fait comme date est une propriété optionnelle elle est automatiquement typé : Date | undefined.
Et Date est non null.

2021-05-07 13:49 UTC, Alezco commented on front/screens/Profile.tsx
> +                      : undefined
Ok !

2021-05-07 13:58 UTC, Alezco requested changes

2021-05-07 14:03 UTC, benguedj commented on front/constants/Labels.ts
> +  dateFormat: "dd/mm/yyyy",
C'est un peu différent car dans la constante de formats c'est "mm" en majuscule dateFR: "dd/MM/yyyy".
La c'est le label par défaut du bouton pour afficher le datePicker lorsqu'aucune date n'a été saisie.

2021-05-07 14:03 UTC, benguedj commented on front/constants/localizations.ts
> +  frFR: "fr-FR	",
Ouups

2021-05-07 15:54 UTC, Alezco approved these changes

2021-05-10 10:36 UTC, yannickjacqueline requested changes

2021-05-10 12:25 UTC, yannickjacqueline commented on front/constants/shadow.constants.ts
> +  offsetWidth: 0,
J'suis d'accord que c'est discutable, je partais seulement du principe qu'on pouvait potentiellement changer la largeur en une valeur supérieure à zéro, mais pour l'instant ça peut rester 0 ouais

2021-05-10 13:05 UTC, merged