feat(matomo): ajoute le tracking avec Matomo
SocialGouv/1000jours pull request #225
Opened 2021-05-21 08:58 UTC by Alezco

2021-05-21 12:15 UTC, Alezco commented
Closes #43

2021-05-21 15:03 UTC, yannickjacqueline commented on front/App.tsx
> +import { matomoInstance } from "./utils/tracker-utils";
Pourquoi pas ajouter le `tracker-utils` dans le fichier `index` du dossier `utils` et faire `import { matomoInstance } from "./utils";`

2021-05-25 10:51 UTC, yannickjacqueline requested changes

2021-05-25 10:51 UTC, yannickjacqueline commented on front/screens/ArticleDetail.tsx
>  import Labels from "../constants/Labels";
```suggestion
import { Colors, Labels } from "../constants";
```

2021-05-25 10:51 UTC, yannickjacqueline commented on front/screens/Profile.tsx
> +import { TrackingEvent } from "../utils/tracker.util";
Import le fichier tracker.util dans l'index et faire `import { StorageUtils, TrackerEvent } from "../utils";` ?

2021-05-25 10:53 UTC, yannickjacqueline commented
Si t'es chaud aussi, pourquoi pas repasser sur les fichiers à renommer avec la nouvelle façon : nomDuFichier.component.tsx

2021-05-25 12:33 UTC, yannickjacqueline approved these changes

2021-05-25 12:35 UTC, merged