feat: 🎸 Ajoute le menu ainsi que les CGU et Mentions Légales
SocialGouv/1000jours pull request #226
Opened 2021-05-21 13:58 UTC by benguedj

✅ Closes: #214, #29

2021-05-21 15:12 UTC, yannickjacqueline commented on front/components/Backdrop.tsx
> +import * as React from "react";
Pourquoi pas renommer le fichier en `backdrop.component.tsx`
Et pareil pour les autres composants créés

2021-05-21 15:12 UTC, yannickjacqueline commented on front/screens/ConditionsOfUse.tsx
> +import { getAssetsAsync } from "../utils/asset.util";
Pourquoi pas importer le `asset.util` dans le fichier `index.ts` du dossier `utils` et faire du coup `import { getAssetsAsync } from "../utils";`

2021-05-25 07:19 UTC, benguedj commented on front/components/Backdrop.tsx
> +import * as React from "react";
Je sais pas, si on renomme ceux là il faudrait renommer tous les composant du dossier components

2021-05-25 07:53 UTC, yannickjacqueline commented on front/components/Backdrop.tsx
> +import * as React from "react";
Pour le reste on le fera au fur et à mesure qu'on revient dessous 😉

2021-05-25 09:54 UTC, Alezco requested changes

2021-05-25 09:54 UTC, Alezco commented on front/assets/html/mentions_legales.html
> +<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
Je crois qu'il y a pas mal de nommages pour les fichiers, à uniformiser. Je crois que le snake_case devrait s'aligner sur les autres avec du kebab-case ou du PascalCase/camelCase

2021-05-25 09:54 UTC, Alezco commented on front/components/Modal.tsx
> +  content: JSX.Element;
Plutôt `ReactNode` ?

2021-05-25 09:54 UTC, Alezco commented on front/screens/ConditionsOfUse.tsx
> +    void AssestUtils.getAssetsAsync(htmlFile as string).then((asset: Asset) => {
Cette logique est sûrement à isoler dans un composant qui gère la logique du rendu HTML. Ensuite, appeler ce composant avec le html des conditions d'utilisation et des mentions légales

2021-05-25 09:54 UTC, Alezco commented on front/utils/asset.util.tsx
> +    return newAsset;
Peut se simplifier en retirant le `return` et l'accolade

2021-05-25 10:12 UTC, benguedj commented on front/assets/html/mentions_legales.html
> +<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
Je mets la recommendation W3C non ? (https://www.w3.org/QA/2002/04/valid-dtd-list.html)
=> <!DOCTYPE html>

2021-05-25 12:07 UTC, Alezco approved these changes

2021-05-25 12:10 UTC, yannickjacqueline commented on front/components/Backdrop.tsx
> +import * as React from "react";
@benguedj t'as pas modifié tous les noms de fichiers que t'as créés, si ?

2021-05-25 12:11 UTC, benguedj commented on front/components/Backdrop.tsx
> +import * as React from "react";
oué jsuis entrain de le faire

2021-05-25 12:55 UTC, benguedj commented on front/components/Backdrop.tsx
> +import * as React from "react";
J'ai renommé le composant "Icomoon", du coup il y a pas mal de fichiers modifiés mais c'est juste le chemin des imports qui change normalement

2021-05-25 13:05 UTC, yannickjacqueline approved these changes

2021-05-25 13:06 UTC, merged