Afficher poi code postal
SocialGouv/1000jours pull request #244
Opened 2021-05-31 17:03 UTC by yannickjacqueline

Si vous voulez tester : 
- côté Strapi, créer quelques adresses dans Cartographie POIS (vous pouvez ne renseigner que le nom, adresse, code postal et commune, et l'outil de géocodage va récupérer les coordonnées GPS et les remplir automatiquement, gros merci à Adrien :D )
- côté mobile, tapez un code postal dans la carto, et vous devriez être déplacés sur la ville et voir les marqueurs rouges ou un message d'erreur sinon

Le composant `TabAroundMeScreen` commence à être imposant (200 lignes), je vais de toute façon continuer à travailler dessus pour les prochaines US, donc il sera refactorisé si besoin ;)

2021-05-31 20:26 UTC, risseraka requested changes
Des remarques plus cosmétiques qu'autre chose.
Je laisse les experts front approfondir pour le reste.

2021-05-31 20:26 UTC, risseraka commented on front/constants/databaseQueries.constants.ts
> +      geocode_adresse
Regrouper les paramètres `geocode_`

2021-05-31 20:26 UTC, risseraka commented on front/screens/tabAroundMeScreen.component.tsx
> +  ); // Variable utilisée pour trigger le useEffect lors du clic sur le bouton Rechercher
J'ai une préférence pour les commentaires sur une ligne différente, au dessus, comme les commentaires JSDoc des fonctions, etc.

2021-05-31 20:26 UTC, risseraka commented on front/screens/tabAroundMeScreen.component.tsx
> +    if (postalCodeInput.length === AroundMeConstants.POSTAL_CODE_MAX_LENGTH) {
Un leave-early en inversant la condition permettrait de désindenter le bloc.

2021-05-31 20:26 UTC, risseraka commented on front/screens/tabAroundMeScreen.component.tsx
> +      if (data) {
Même chose qu'au dessus (leave-early).

2021-05-31 20:26 UTC, risseraka commented on front/screens/tabAroundMeScreen.component.tsx
> +          fetchedData.length > 0
Si `fetchData.length === 0`, on a déjà un array vide, non ?
Pourquoi ne pas `setPoisArray` directement avec `fetchedData` ?

2021-05-31 20:26 UTC, risseraka commented on front/type/aroundMe.types.ts
> +  geocode_adresse: string;
Rassembler les `geocode_`.

2021-06-01 08:28 UTC, yannickjacqueline commented on front/screens/tabAroundMeScreen.component.tsx
> +          fetchedData.length > 0
Complètement x) j'ai même mis le slice directement, je pensais pas mais un slice sur un array vide retourne un array vide donc ça reviens au même au final, très bonne remarque ;)

2021-06-01 08:41 UTC, merged