feat(etape): retourne l'étape courante en fonction des informations fournies
SocialGouv/1000jours pull request #45
Opened 2021-03-10 12:50 UTC by risseraka

2021-03-10 13:37 UTC, Alezco requested changes

2021-03-10 13:37 UTC, Alezco commented on back/strapi/api/etape/controllers/etape.js
> +const ENFANT_3_MOIS = JOUR * 30 * 3;
Petit doute sur ce calcul : tous les mois ne font pas 30 jours. Pour être plus précis, peut-être utiliser `date-fns` ?

2021-03-10 13:37 UTC, Alezco commented on back/strapi/api/etape/controllers/etape.js
> +const calcGrossesse = (ctx, terme) => {
Typer les paramètres et le type de retour de cette fonction

2021-03-10 13:37 UTC, Alezco commented on back/strapi/api/etape/controllers/etape.js
> +const calcEnfant = (ctx, naissance) => {
Idem ici, typer les paramètres et le retour

2021-03-10 13:37 UTC, Alezco commented on back/strapi/api/etape/controllers/etape.js
> +module.exports = {
Possible de plutôt stocker cet objet dans un const et de faire un `export const` ou un `export default` ?

2021-03-10 13:37 UTC, Alezco commented on back/strapi/api/etape/controllers/etape.js
> +      !ctx.request.body ||
Avec l'optionnal chaining de TypeScript, on peut simplifier ce if : https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html

2021-03-10 13:37 UTC, Alezco commented on back/strapi/api/etape/controllers/etape.js
> +      !ctx.request.body ||
```suggestion
      !ctx.request.body?.input?.infos
```

2021-03-10 13:37 UTC, Alezco commented on back/strapi/api/etape/controllers/etape.js
> +    const infos = ctx.request.body.input.infos;
On peut destructurer `infos` directement ici pour obtenir `grossesse`, `enfant` et `enfants` et simplifier l'écriture plus tard

2021-03-10 13:37 UTC, Alezco commented on back/strapi/api/etape/controllers/etape.js
> +      let id;
```suggestion
      const id = infos.grossess ? calcGrossesse(ctx, date) : calcEnfant(ctx, date);
```

2021-03-12 14:26 UTC, Alezco requested changes

2021-03-12 14:26 UTC, Alezco commented on back/strapi/api-src/etape/controllers/etape.ts
> +  projet: Boolean,
`boolean` avec un b minuscule est à privilégier : https://www.tutorialsteacher.com/typescript/typescript-boolean

2021-03-12 14:26 UTC, Alezco commented on back/strapi/api-src/etape/controllers/etape.ts
> +  badRequest: (str: String) => void,
Possible de trouver un meilleur nom que `str` ?

2021-03-12 14:26 UTC, Alezco commented on back/strapi/api-src/etape/controllers/etape.ts
> +const calcGrossesse = (ctx: Context, terme: Date): Number | void => {
Idem ici, utiliser `number` en type primitif plutôt qu'en objet

2021-03-12 14:26 UTC, Alezco commented on back/strapi/api-src/etape/controllers/etape.ts
> +  const grossesseDebut = addWeeks(terme, -GROSSESSE_TOTAL_SEMAINES_SA);
Préférer la méthode `subWeeks` de `date-fns` pour plus de lisibilité

2021-03-15 08:58 UTC, Alezco approved these changes

2021-03-15 08:59 UTC, risseraka commented
Merci pour ta vigilance. 👍

2021-03-15 09:03 UTC, merged