chore(initialisation): ajoute les schémas de base et des exemples de données
SocialGouv/1000jours pull request #6
Opened 2021-02-17 12:11 UTC by risseraka

2021-03-01 14:40 UTC, risseraka commented
J'ai ajouté `strapi` à la PR avec `hasura` pour la gestion de contenu. 🎉 
Il faudra qu'on teste ensemble si vous arrivez à faire tourner le back à partir de zéro avec la PR avant de merge. @benguedj @Alezco

2021-03-03 11:03 UTC, revolunet approved these changes

2021-03-05 09:29 UTC, risseraka commented
@benguedj @Alezco si vous arrivez à lancer le serveur en local, je vous propose de merger la PR.
Le schéma n'est pas définitif (notamment pour les articles et leur structure, des choses plus dynamiques sont à venir pour pouvoir gérer les différents types de modèles), mais c'est utilisable dans un premier temps !

2021-03-05 14:50 UTC, Alezco requested changes

2021-03-05 14:50 UTC, Alezco commented on back/strapi/public/robots.txt
> +# User-Agent: *
A décommenter ?

2021-03-05 14:50 UTC, Alezco commented on back/docker-compose.yaml
> +      POSTGRES_PASSWORD: milleetunjoursdebebe
Mettre le mot de passe dans un .env et pas en clair

2021-03-05 14:50 UTC, Alezco commented on back/docker-compose.yaml
> +      DATABASE_PASSWORD: milleetunjoursdebebe
Idem ici

2021-03-05 14:50 UTC, Alezco commented on back/docker-compose.yaml
> +      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
Mettre en variable d'env pour le désactiver en production ?

2021-03-05 14:50 UTC, Alezco commented on back/docker-compose.yaml
> +      HASURA_GRAPHQL_ADMIN_SECRET: hasurac'estpasmal
A mettre en secret aussi

2021-03-05 14:50 UTC, Alezco commented on back/strapi/.eslintrc
> +{
A voir s'il ne faudrait pas plutôt extend l'ESLint/Prettier de la Fabrique : https://github.com/SocialGouv/linters

2021-03-05 14:50 UTC, Alezco commented on back/strapi/extensions/users-permissions/config/jwt.js
> +  jwtSecret: process.env.JWT_SECRET || '87f040e3-16b7-40c3-b174-b52d20d1aae6'
Safe de garder ça en clair ?

2021-03-05 14:50 UTC, Alezco commented on back/strapi/package.json
> +  "devDependencies": {},
Ligne à supprimer ?

2021-03-05 14:50 UTC, Alezco commented on back/strapi/package.json
> +    "name": "A Strapi developer"
```suggestion
    "name": "Fabrique des ministère sociaux"
```

2021-03-05 14:50 UTC, Alezco commented on back/strapi/plugins/wysiwyg/admin/src/containers/HomePage/index.js
> +// import PropTypes from 'prop-types';
Commentaire à supprimer

2021-03-05 14:54 UTC, risseraka commented on back/docker-compose.yaml
> +      POSTGRES_PASSWORD: milleetunjoursdebebe
Merci pour la revue !
Ce docker-compose est un fichier de dev, en prod ce sera un fichier différent, configuré dans la plateforme par le SRE, d'après ce que j'ai compris de ce que @revolunet nous a expliqué.

2021-03-05 14:55 UTC, risseraka commented on back/strapi/plugins/wysiwyg/admin/src/containers/HomePage/index.js
> +// import PropTypes from 'prop-types';
J'avoue que c'est du copié-collé d'un tuto, j'ai pas fait gaffe.

2021-03-05 14:57 UTC, risseraka commented on back/strapi/.eslintrc
> +{
Est-ce qu'on peut faire passer ça dans une autre PR ?
J'ai peur que ça prenne un peu trop de temps et recule d'autant le merge, sachant que tout le dossier (à l'exception du code du plugin WYSIWYG) est généré par le docker strapi, je n'ai pas fait de modif. 🤔

2021-03-05 14:59 UTC, Alezco commented on back/strapi/.eslintrc
> +{
Pas de problème, du moment qu'on a ça à l'esprit 👍

2021-03-05 15:01 UTC, risseraka commented on back/strapi/.eslintrc
> +{
Je fais ça dans la foulée.

2021-03-05 15:02 UTC, Alezco approved these changes

2021-03-05 15:03 UTC, risseraka commented on back/strapi/extensions/users-permissions/config/jwt.js
> +  jwtSecret: process.env.JWT_SECRET || '87f040e3-16b7-40c3-b174-b52d20d1aae6'
On peut le supprimer en effet et le set dans le docker-compose pour ne pas oublier.

2021-03-05 15:05 UTC, Alezco approved these changes

2021-03-05 17:12 UTC, merged