fix(carto): correction sur la récupération de la localisation
SocialGouv/1000jours pull request #675
Opened 2021-09-09 16:01 UTC by yannickjacqueline

Closes #651

2021-09-09 16:09 UTC, risseraka commented on front/screens/aroundMe/searchByPostalCode.component.tsx
> +        } catch (ex: unknown) {}
Hummm, ça sent la boucle infinie s'il y a une erreur, ça !

2021-09-09 16:16 UTC, yannickjacqueline commented on front/screens/aroundMe/searchByPostalCode.component.tsx
> +        } catch (ex: unknown) {}
Ah il a raison le bougre !
Je vais trouver une autre solution

2021-09-09 16:18 UTC, risseraka commented on front/screens/aroundMe/searchByPostalCode.component.tsx
> +        } catch (ex: unknown) {}
Peut-être un `setTimeout` ou `setInterval` avec un retry max de 2 ou 3, histoire de pas rester dessus indéfiniment ?

2021-09-09 16:32 UTC, yannickjacqueline commented on front/screens/aroundMe/searchByPostalCode.component.tsx
> +        } catch (ex: unknown) {}
Ouais je pense que je vais prendre cette solution, mais c'est assez aléatoire quand je mets pas de timeout, des fois il n'y a besoin que de 3-4 tentatives, et des fois ça monte à 40, donc je pense qu'en mettant un intervalle entre chaque tentative ça ira. Je peux aussi vérifier selon l'exception qu'on se prend
Je vais tester tout ça, merci en tout cas ;)

2021-09-14 07:43 UTC, risseraka requested changes

2021-09-14 07:43 UTC, risseraka commented on front/constants/Labels.ts
> +      "Location provider is unavailable. Make sure that location services are enabled.",
C'est un message qui vient de l'extérieur et non un label que l'on voudrait afficher, il faudrait peut-être le mettre ailleurs ?

2021-09-14 07:43 UTC, risseraka commented on front/screens/aroundMe/searchByPostalCode.component.tsx
> +      while (!locationSuccess) {
Pas convaincu par ce `while`, est-ce qu'il n'y a pas un risque de bloquer le thread, malgré le `await` ?

Aussi, j'ai peur que ça spam un peu sans contrôle sur le timing des "retry".

Est-ce que tu arrives à reproduire l'erreur et faire planter la géoloc volontairement pour tester le code ?

2021-09-14 07:43 UTC, risseraka commented on front/screens/aroundMe/searchByPostalCode.component.tsx
> +            !JSON.stringify(ex).includes(
Est-ce qu'on déterminer si la position n'est pas récupérée à cause d'un manque d'activation de la géoloc ?
Si oui, est-ce qu'on afficherait pas un message d'erreur en fonction ?

2021-09-15 15:07 UTC, yannickjacqueline commented on front/screens/aroundMe/searchByPostalCode.component.tsx
> +            !JSON.stringify(ex).includes(
En fait, si on n'autorise pas la géoloc, ça tombe dans le cas ligne 60, et du coup on a un petit message comme quoi il faut autoriser la géoloc dans les paramètres du téléphone.
En revanche, si on autorise l'accès à la géoloc mais qu'on ne l'active pas, la recherche est lancée sur la dernière zone enregistrée (et sur la région parisienne par défaut), on avait vu ça à l'oral avec Maxime

2021-09-15 15:12 UTC, yannickjacqueline commented on front/screens/aroundMe/searchByPostalCode.component.tsx
> +      while (!locationSuccess) {
Oui, si par exemple le mets le nombre de tentatives max à 2, la recherche s'arrête, et du coup on tombe dans le cas où la géoloc n'est pas activée, à savoir la recherche lancée sur la dernière zone enregistrée

2021-09-15 15:13 UTC, risseraka approved these changes

2021-09-15 15:13 UTC, merged