Parenthèque
SocialGouv/1000jours pull request #677
Opened 2021-09-13 13:41 UTC by alebret

2021-09-21 13:30 UTC, risseraka requested changes

2021-09-21 13:30 UTC, risseraka commented on front/components/document/documentCard.component.tsx
> +      console.log(err);
Idem.

2021-09-21 13:30 UTC, risseraka commented on front/components/timeline/timelineStepLibrary.component.tsx
> +  const getStepNumStyles = () => {
On peut enlever l'accolade.

2021-09-21 13:45 UTC, risseraka requested changes

2021-09-21 13:45 UTC, risseraka commented on front/components/document/documentCard.component.tsx
> +const DocumentCard: FC<Props> = ({ document }) => {
On peut enlever les accolades et le return.

2021-09-21 13:45 UTC, risseraka commented on front/components/document/documentCard.component.tsx
> +    console.warn(err);
Est-ce qu'on veut garder ce debug ?
Il remonte dans sentry ?

2021-09-21 13:45 UTC, risseraka commented on front/components/timeline/timelineStepLibrary.component.tsx
> +  const getStepStyles = () => {
ON peut enlever les accolades et le `return`.

2021-09-21 13:57 UTC, alebret commented on front/components/document/documentCard.component.tsx
> +    console.warn(err);
bonne question ?! je n'ai pas encore utilisé sentry ici

2021-09-22 14:58 UTC, risseraka approved these changes

2021-09-22 15:18 UTC, yannickjacqueline approved these changes

2021-09-22 15:50 UTC, merged