feat(carto): gestion zoom + refacto
SocialGouv/1000jours pull request #718
Opened 2021-09-28 15:21 UTC by yannickjacqueline

Closes #645 

Solution retenue :  
à chaque recherche par code postal ou chaque géolocalisation, je vais chercher le nombre d'habitants de la ville recherchée et selon ce nombre, je réduis la zone de recherche. Par exemple pour Paris, la zone sera relativement petite, et un peu plus grande pour les métropoles françaises. Sinon j'applique une zone par défaut.
J'ai aussi bloqué le zoom minimal, afin de ne pas donner la possibilité de dézoomer sur tout Paris par exemple, et ainsi limiter le nombre de POIs récupérés.

Cette solution n'est pas parfaite, mais elle va suffire pour le moment.

2021-09-28 16:05 UTC, alebret commented on front/constants/aroundMe.constants.ts
> +export const POPULATION_STEP_PARIS = 2000000;
tu peux peut-être les renommer, on pourrait croire que tu ne vérifies que ces 3 villes.

2021-09-28 16:19 UTC, risseraka requested changes

2021-09-28 16:19 UTC, risseraka commented on front/utils/aroundMe.util.ts
> +    else if (population > AroundMeConstants.POPULATION_STEP_MARSEILLE)
Pas besoin de `else if` s'il y a un `return` dans le `if` précédent.

2021-09-28 16:19 UTC, risseraka commented on front/utils/aroundMe.util.ts
> +    else return AroundMeConstants.DEFAULT_DELTA;
On peut enlever ce dernier `return` vu que le cas par défaut est géré juste après.

2021-09-29 08:12 UTC, alebret approved these changes

2021-09-29 08:39 UTC, merged