feat: 🎸 je consulte le détail d'un article (v1)
SocialGouv/1000jours pull request #77
Opened 2021-03-29 11:40 UTC by benguedj

✅ Closes: #28

2021-03-29 12:29 UTC, Alezco requested changes

2021-03-29 12:29 UTC, Alezco commented on front/components/form/Button.tsx
> +  icon?: React.ReactElement;
```suggestion
  icon?: React.ReactNode;
```

2021-03-29 12:29 UTC, Alezco commented on front/components/form/Button.tsx
> +  icon?: React.ReactElement;
Peut-être que tu pourras retirer le `?` avec `ReactNode` puisque le type comprend `undefined` il me semble

2021-03-29 12:29 UTC, Alezco commented on front/package.json
> +    "expo-font": "^8.4.0",
Pourquoi un downgrade ?

2021-03-29 12:29 UTC, Alezco commented on front/screens/ArticleDetail.tsx
> +      <View>
A isoler dans son propre composant ? On risque d'en avoir besoin à nouveau dans d'autres fichiers

2021-03-29 12:29 UTC, Alezco commented on front/screens/ArticleDetail.tsx
> +  } else {
Les `else` ne sont probablement pas nécessaires. Je pense que `loading`, `error` et `data` sont 3 états différents qui ne peuvent pas valoir quelque chose en même temps. Je pense que le code peut être simplifié comme dans cet exemple : https://www.apollographql.com/docs/react/data/queries/#executing-a-query

2021-03-29 12:29 UTC, Alezco commented on front/screens/ArticleDetail.tsx
> +              <Button
Ce bouton retour est peut-être aussi à isoler dans son propre composant puisqu'il sera sûrement utile ailleurs à l'avenir

2021-03-29 12:29 UTC, Alezco commented on front/screens/ListArticles.tsx
> +        <ActivityIndicator size="large" />
Même commentaire ici pour le composant de Loading à sortir de ce fichier (peut-être aussi celui d'erreur), et aussi sur les `if else`

2021-03-29 12:29 UTC, Alezco commented on front/screens/ListArticles.tsx
> +      console.log(error);
A retirer ?

2021-03-29 12:29 UTC, Alezco commented on front/screens/ListArticles.tsx
> +              return (
L'écriture peut être simplifiée en retirant le return et les accolades

2021-03-29 12:29 UTC, Alezco commented on front/screens/ListArticles.tsx
> +                      <HTML
A changer peut-être à l'avenir. Je n'aime pas beaucoup l'idée d'avoir une webview pour la description sur chaque élément de la liste. L'idéal serait peut-être d'avoir depuis le back-end une description ou un résumé de l'article sous forme de string et pas de HTML pour simplifier le code ici. @risseraka Qu'en penses-tu ?

2021-03-29 14:53 UTC, benguedj commented on front/package.json
> +    "expo-font": "^8.4.0",
J'ai downgrade la version car la v9 ne fonctionne pas bien avec les fonts custom, j'ai commencé à créer une font d'icônes ça sera beaucoup plus simple à gérer pour changer la couleur et importer chaque icône à chaque fois. Je sais pas si tu connais icomoon c'est un outil en ligne qui permet de générer des fonts à partir de svg (https://icomoon.io/app/#/select)

2021-03-29 17:40 UTC, risseraka commented on front/screens/ListArticles.tsx
> +                      <HTML
C'est à configurer.
S'il n'y a pas de besoin d'éditorialiser le résumé, alors on peut s'en tirer avec un champ de type description.
À valider avec le métier ?

2021-03-30 09:29 UTC, Alezco approved these changes

2021-03-30 09:30 UTC, merged