feat(recherche): recherche articles
SocialGouv/1000jours pull request #807
Opened 2021-10-15 12:08 UTC by alebret

Yannick : pour info, je n'ai volontairement pas touché ni modifié les composants déjà existants, il y a donc des doublons mais c'est pour la même raison que le questionnaire EPDS : je ne sais pas si les choses rechangeront à l'avenir, donc je ferai un nettoyage prochainement si nécessaire

2022-01-14 09:54 UTC, alebret commented on front/constants/Labels.ts
> +      "Afin de vous apporter une aidée personnalisée, veuillez renseigner votre localisation :",
il y a des fautes

2022-01-14 09:58 UTC, alebret commented on front/screens/search/poiList.component.tsx
> +      // etapes: savedFilters?.etapes ? savedFilters.etapes : [],
A supprimer ? sinon expliquer pourquoi c'est en commentaire

2022-01-14 09:59 UTC, alebret commented on front/screens/search/poiList.component.tsx
> +      // thematiques: savedFilters?.thematiques ? savedFilters.thematiques : [],
A supprimer ? sinon expliquer pourquoi c'est en commentaire

2022-01-14 09:59 UTC, alebret commented on front/screens/search/poiList.component.tsx
> +          // if (filterWasSaved) {
???

2022-01-14 10:01 UTC, risseraka requested changes

2022-01-14 10:01 UTC, risseraka commented on front/screens/search/tabSearchScreen.component.tsx
> +  if (articles.length > 0) {
J'inverserais le `if` pour traiter le cas le plus simple et désindenter tout ce gros morceau de code.

2022-01-14 10:03 UTC, yannickjacqueline commented on front/screens/ArticleDetail.tsx
> +                if (goBack) goBack();
C'est justement une fonction facultative passée dans les props, donc c'est pour vérifier qu'elle soit là pour l'appeler

2022-01-14 10:39 UTC, alebret commented
@yannickjacqueline Il n'y a pas moyen de rajouter qq TU ? Je n'en vois aucun

2022-01-17 16:12 UTC, risseraka requested changes

2022-01-17 16:12 UTC, risseraka commented on front/screens/search/tabAroundMeInstruction.component.tsx
> +    articles.map((article) => {
Un map sert à créer un tableau de la même longueur que le tableau d'origine.
Ici, la fonction itérative ne retourne rien et la valeur de retour du map n'est pas utilisée.

Si la boucle ne retourne rien : forEach.
Si elle retourne un tableau plus petit du même type : filter.
Si elle retourne un tableau de type différent : reduce.

2022-01-17 16:12 UTC, risseraka commented on front/screens/search/tabAroundMeInstruction.component.tsx
> +            .map((finalType) => finalType.nom)
`map` + `includes`, ça ressemble à un `some` (bonus : ça s'arrête au premier match).

2022-01-17 16:12 UTC, risseraka commented on front/screens/search/tabAroundMeInstruction.component.tsx
> +        pois.map((poi) => finalCartographieTypes.push(poi));
`map` pour ajouter dans un tableau, c'est plutôt `arr.push(...poi)`.

2022-01-17 16:12 UTC, risseraka commented on front/screens/search/tabAroundMeInstruction.component.tsx
> +
Au final, tout ce code un peu obscure, ça ressemble à un `flatMap` : on construit un tableau à partir de tableaux (vide ou non, en fonction de l'itération).

2022-01-24 21:32 UTC, merged