feat(epds): choix du mode de contact
SocialGouv/1000jours pull request #905
Opened 2021-12-02 09:33 UTC by alebret

2021-12-08 18:00 UTC, risseraka requested changes

2021-12-08 18:00 UTC, risseraka commented on front/screens/epdsSurvey/beContacted/beContactedForm.test.ts
> +    it("Have select email and complete email", () => {
Je trouve la description du test un peu étrange grammaticalement.
(`Have selected` ?)

2021-12-09 08:24 UTC, alebret commented on front/constants/Labels.ts
> +      formSend: "Votre demande de contact a bien été prise en compte. ",
C'est normal, car il y a une autre phrase derrière. Sinon les 2 sont collées.

2021-12-09 08:26 UTC, alebret commented on front/constants/Labels.ts
> +        "Vous devriez recevoir un email d’Elise dans les 48h. \nPensez bien à vérifier dans vos spams.",
C'est Eslint qui fait ça tout seul.

2021-12-15 09:38 UTC, benguedj approved these changes

2021-12-16 08:58 UTC, merged